site_name: Foothills Programming Course


nav:
  - Home: index.md
  - Learning Objectives: Learning.md

  - Getting Started:
    - Programs: Getting Started/Programs.md

  - Week 1 - Syntax:
    - Syntax: W1 Syntax/Home.md
  
  - Week 2 - Variables:
    - Variables: W2 Variables/Home.md

  - Week 3 - Control Flow:
    - Control Flow: W3 Control Flow/Home.md
  
  - Week 4 - Functions:
    - Function: W4 Functions/Home.md
  
  - Week 5 - Classes:
    - Classes: W5 Classes/Home.md
  
  - Week 6 - Intro to FRC Ecosystem:
    - Intro to FRC Ecosystem: W6 Intro FRC/Home.md
  
  - week 7 - Sensors And Inputs:
    - Sensors And Inputs: W7 Sensors And Inputs/Home.md
  
  - Week 8 - Actuators:
    - Actuators: W8 Actuators/Home.md
  
  - Week 9 - Subsystems:
    - Subsystems: W9 Subsystems/Home.md
  
  - Week 10 - Commands:
    - Commands: W10 Commands/Home.md
  
  - Week 11 - Autonomous:
    - Autonomous: W11 Auto/Home.md
  
  - Week 12 - Github:
    - Github: W13 Github/Home.md
  
  - Weel 13 + 14 - Assignments:
    - Assignments: Assignments/Home.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
  - pymdownx.details
  - abbr

theme: readthedocs