site_name: Foothills Programming Course


nav:
  - Home: index.md
  - Learning Objectives: Learning.md

  - Getting Started:
    - Programs: Getting Started/Programs.md

  - Week 1 - Syntax:
    - Syntax: W1 Syntax/Home.md
  
  - Week 2 - Variables:
    - Variables: W2 Variables/Home.md

  - Week 3 - Control Flow:
    - Control Flow: W3 Control Flow/Home.md
  
  - Week 4 - Functions:
    - Function: W4 Functions/Home.md
  
  - Week 5 - Classes:
    - Classes: W5 Classes/Home.md
  
  - Week 6 - Intro to FRC Ecosystem:
    - Intro to FRC Ecosystem: W6 Intro FRC/Home.md
  
  - Week 7 - Subsystems:
    - Subsystems: W7 Subsystems/Home.md
  
  - Week 8 - Commands:
    - Commands: W8 Commands/Home.md
  
  - Week 9 - Autonomous:
    - Autonomous: W9 Auto/Home.md
  
  - Week 10 - Vision:
    - Vision: W10 Vision/Home.md
  
  - Assignments:
    - Assignments: Assignments/Home.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list

theme: readthedocs